feat: print entity identifer in errors for visibility
When dealing with many errors, it can be hard to map the error messages (which all appear together at the very end of the output) to the entities (which appear all before). This PR adds information about the kind of entity and the entity identifier to the error messages.

*Before (showing just one error for brevity, and coincidentally the identifier is also in the error message - however, this really matters esp. when there are dozens of errors and the errors have less detail):*
```ShellSession
$ deck sync -s .
creating consumer acl21
Summary:
  Created: 0
  Updated: 0
  Deleted: 0
Error: 1 errors occurred:
		while processing event: {Create} failed: 409 Conflict {"message":"UNIQUE violation detected on '{username=\"acl21\"}'","name":"unique constraint violation","fields":{"username":"acl21"},"code":5}
```

*After:*
```ShellSession
$ deck sync -s .
creating consumer acl21
Summary:
  Created: 0
  Updated: 0
  Deleted: 0
Error: 1 errors occurred:
		while processing event: {Create} consumer acl21 failed: 409 Conflict {"message":"UNIQUE violation detected on '{username=\"acl21\"}'","name":"unique constraint violation","fields":{"username":"acl21"},"code":5}
```

Notice the additional detail in `while processing event: {Create} consumer acl21 failed:`.

From #199